apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-nodejs-proxy.fullname" . }}
  labels:
    app: {{ include "helm-nodejs-proxy.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-nodejs-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-nodejs-proxy.name" . }}
    spec:
      containers:
        - name: nodejs-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: PROXY_SOURCE_URL
              value: "{{ .Values.env.PROXY_SOURCE_URL }}"
            - name: PROXY_REPLACE_URL
              value: "{{ .Values.env.PROXY_REPLACE_URL }}"
            - name: PROXY_TARGET_URL
              value: "{{ .Values.env.PROXY_TARGET_URL }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
