apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-nodejs-proxy.fullname" . }}
  labels:
    app: {{ include "helm-nodejs-proxy.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "helm-nodejs-proxy.name" . }}
