apiVersion: v1
kind: Service
metadata:
  name: helm-nodejs-proxy
  labels:
    app: helm-nodejs-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: helm-nodejs-proxy