name: Helm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.9.0

    - name: Helm Lint
      run: helm lint ./helm

    - name: Create charts directory
      run: mkdir -p ./charts

    - name: Helm Package
      run: helm package ./helm --destination ./charts

    - name: List packaged charts
      run: ls -la ./charts

    - name: Upload Helm Charts as Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: helm-charts
        path: ./charts/*.tgz

    - name: Prepare GitHub Pages directory
      run: mkdir -p ./docs

    - name: Move packaged chart to docs
      run: mv ./charts/*.tgz ./docs/

    - name: Create Helm repo index
      run: helm repo index ./docs --url https://tsgames.github.io/nodejs-proxy-server

    - name: Commit and push to GitHub Pages
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add ./docs
        git commit -m "Update Helm chart repo"
        git push origin main