name: Helm CI

on:
  push:
    branches:
      - main
    tags:        
      - '**'   
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.9.0

    - name: Helm Lint
      run: helm lint ./helm

    - name: Create charts directory
      run: mkdir -p ./charts

    - name: Helm Package
      run: helm package ./helm --destination ./charts

    - name: List packaged charts
      run: ls -la ./charts

    - name: Upload Helm Charts as Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: helm-charts
        path: ./charts/*.tgz

  # 8. Configure git user for committing changes
    - name: Set up Git user
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    # 9. Commit the changes to the docs/ folder
    - name: Commit changes
      run: |
        git add ./charts/*.tgz
        git commit -m "Update Helm chart and index on $(date +'%Y-%m-%d')"
        git push origin main